# POST http://localhost:4000/signup
# Content-Type: application/json

# {
#     "fullName": "First Last",
#     "username": "usernm",
#     "email": "fl@testing.com",
#     "password": "test123"
# }

GET http://localhost:4000/login/reactclient@react.com
Content-Type: application/json