GET http://localhost:4000/login/
Content-Type: application/json

{
    "email": "fl@testing.com",
    "password": "test123"
}


# POST http://localhost:4000/signup
# Content-Type: application/json

# {
#     "fullName": "First Last",
#     "username": "usernm",
#     "email": "fl@testing.com",
#     "password": "test123"
# }